version: '3.1'

services:
    web:
        container_name: avalon-web
        build: .
        command: ["./docker/wait-for-db.sh", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - REDIS_HOSTNAME=redis
            - REDIS_DB_NUMBER=0
            - REDIS_DB_PREFIX=local
        depends_on:
            - db
            - redis
    db:
        container_name: avalon-db
        image: postgres:9.6
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
    redis:
        container_name: avalon-redis
        image: redis:3.2.4-alpine
        ports:
            - "6379:6379"
