# Generated by Django 2.1.7 on 2019-03-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=5)),
                ('role', models.CharField(choices=[('soldier', '兵士'), ('merlin', 'マーリン'), ('mordred', 'モードレッド'), ('assassin', '暗殺者')], max_length=12)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('poll1', models.BooleanField(null=True)),
                ('poll2', models.BooleanField(null=True)),
                ('poll3', models.BooleanField(null=True)),
                ('poll4', models.BooleanField(null=True)),
                ('poll5', models.BooleanField(null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalon.Player')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='avalon.Player')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='avalon.Player')),
                ('member3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='avalon.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('result1', models.BooleanField(null=True)),
                ('result2', models.BooleanField(null=True)),
                ('result3', models.BooleanField(null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalon.Player')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q1', to='avalon.Player')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q2', to='avalon.Player')),
                ('member3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q3', to='avalon.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.IntegerField()),
                ('poll', models.IntegerField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalon.Player')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avalon.Room')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='avalon.Room'),
        ),
        migrations.AddField(
            model_name='poll',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='avalon.Quest'),
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='avalon.Room'),
        ),
    ]
